FlatMVC/Areas/Admin/Controllers/GeneralsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using Entity;

namespace FlatMVC.Areas.Admin.Controllers
{
    public class GeneralsController : AdminController
    {
        private FlatContext db = new FlatContext();

        // GET: Admin/Generals
        public ActionResult Index()
        {
            ViewBag.ShowCreateNew = db.General.Count() == 0;

            return View(db.General.FirstOrDefault());
        }

        // GET: Admin/Generals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            General general = db.General.Find(id);
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // GET: Admin/Generals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Generals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LogoURL,SiteTitle,SiteDesc,HeaderTitle,HeaderDescription,CTA1_Title,CTA1_Description,CTA2_Title,CTA2_Button,Address,Email,Phone")] General general, HttpPostedFileBase LogoImage)
        {
            if(LogoImage != null && LogoImage.ContentLength != 0)
            {
                var path = Server.MapPath("/Content/");
                var filename = LogoImage.FileName; //resim.jpg
                LogoImage.SaveAs(path + filename);
                general.LogoURL = LogoImage.FileName;
            }

            if (ModelState.IsValid)
            {
                db.General.Add(general);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(general);
        }

        // GET: Admin/Generals/Edit/5
        public ActionResult Edit()
        {
            General general = db.General.FirstOrDefault();
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // POST: Admin/Generals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SiteTitle,SiteDesc,HeaderTitle,HeaderDescription,CTA1_Title,CTA1_Description,CTA2_Title,CTA2_Button,Address,Email,Phone")] General general, HttpPostedFileBase LogoImage)
        {
            if (LogoImage != null && LogoImage.ContentLength != 0)
            {
                var path = Server.MapPath("/Content/");
                var filename = LogoImage.FileName; //resim.jpg
                LogoImage.SaveAs(path + filename);
                general.LogoURL = LogoImage.FileName;
            } else
            {
                //resim seçilmediyse eski resim kalsın
                var kayit = db.General.FirstOrDefault();
                general.LogoURL = kayit.LogoURL;
                db.Entry(kayit).State = EntityState.Detached;
            }

            if (ModelState.IsValid)
            {
                db.Entry(general).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(general);
        }

        // GET: Admin/Generals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            General general = db.General.Find(id);
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // POST: Admin/Generals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            General general = db.General.Find(id);
            db.General.Remove(general);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlatMVC/Areas/Admin/Views/Generals/Create.cshtml
@model Entity.General

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Generals",FormMethod.Post, new { @enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>General</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LogoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("LogoImage", new { htmlAttributes = new { @class = "form-control", @type="file" } })
                @Html.ValidationMessageFor(model => model.LogoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeaderTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeaderTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeaderTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeaderDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeaderDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeaderDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA1_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA1_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA1_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA1_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA1_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA1_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA2_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA2_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA2_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA2_Button, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA2_Button, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA2_Button, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlatMVC/Areas/Admin/Views/Generals/Delete.cshtml
@model Entity.General

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>General</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LogoURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogoURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SiteTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SiteDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeaderTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeaderTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeaderDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeaderDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA1_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA1_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA1_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA1_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA2_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA2_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA2_Button)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA2_Button)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FlatMVC/Areas/Admin/Views/Generals/Details.cshtml
@model Entity.General

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>General</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LogoURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogoURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SiteTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SiteDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeaderTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeaderTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeaderDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeaderDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA1_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA1_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA1_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA1_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA2_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA2_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTA2_Button)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTA2_Button)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlatMVC/Areas/Admin/Views/Generals/Edit.cshtml
@model Entity.General

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Generals",FormMethod.Post, new { @enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>General</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LogoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("LogoImage", new { htmlAttributes = new { @class = "form-control", @type="file" } })
                @Html.ValidationMessageFor(model => model.LogoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeaderTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeaderTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeaderTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeaderDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeaderDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeaderDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA1_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA1_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA1_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA1_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA1_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA1_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA2_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA2_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA2_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CTA2_Button, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CTA2_Button, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CTA2_Button, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlatMVC/Areas/Admin/Views/Generals/Index.cshtml
@model Entity.General

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Genel Ayarlar</h2>

@if (ViewBag.ShowCreateNew)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.LogoURL)
        </td>
        <td>
            <img src="~/Content/@Model.LogoURL" height="150" />
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.SiteTitle)
        </td>
        <td>
            @Model.SiteTitle
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.SiteDesc)
        </td>
        <td>@Model.SiteDesc</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.HeaderTitle)
        </td>
        <td>@Model.HeaderTitle</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.HeaderDescription)
        </td>
        <td>@Model.HeaderDescription</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.CTA1_Title)
        </td>
        <td>@Model.CTA1_Title</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.CTA1_Description)
        </td>
        <td>@Model.CTA1_Description</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.CTA2_Title)
        </td>
        <td>@Model.CTA2_Title</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.CTA2_Button)
        </td>
        <td>@Model.CTA2_Button</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Address)
        </td>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Email)
        </td>
        <td>@Model.Email</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Phone)
        </td>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink("Düzenle","Edit",null,new { @class="btn btn-primary"})
        </td>
    </tr>
</table>